/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TickBit } from "./TickBit";
export * as factories from "./factories";
export { TickBit__factory } from "./factories/TickBit__factory";
